### ISSUE TITLE
Meta data tag to set push icon not honoured

### ISSUE THREAD

**Issue by cbramley** [ParsePlatform/Parse-SDK-dotNET#39] opened 2015-10-16 15:47 UTC
To set a custom push icon the SDK docs require adding the following meta data tag to the manifest within the `<application>` tag.

`<meta-data android:name="com.parse.push.notification_icon" android:resource="@drawable/icon"/>`

In this version of the SDK no check is made for the presence of that metadata, so only the launcher icon is ever set.

See `IconId` in https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/Parse/Internal/ManifestInfo.cs

**Comment by richardjrossiii** [comment] 2015-10-20 00:28
Thanks for the report! This appears to be a duplicate of #12.

**Comment by richardjrossiii** [comment] 2015-10-20 00:54
Misread the question. This is indeed an issue with the SDK on Xamarin for android.

**Closed** 2015-10-21 20:46 UTC
Labels: needs investigation
