### ISSUE TITLE
MAC OS (Xamarin) no build

### ISSUE THREAD

**Issue by Avatarchik** [ParsePlatform/Parse-SDK-dotNET#189] opened 2016-02-29 21:04 UTC
error
.../Parse-SDK-dotNET-master/AssemblyLister/AssemblyLister.UWP/AssemblyLister.UWP.csproj: error : .../Parse-SDK-dotNET-master/AssemblyLister/AssemblyLister.UWP/AssemblyLister.UWP.csproj: .../Parse-SDK-dotNET-master/AssemblyLister/AssemblyLister.UWP/AssemblyLister.UWP.csproj could not import "$(MSBuildExtensionsPath32)\Microsoft\Portable\$(TargetFrameworkVersion)\Microsoft.Portable.CSharp.targets"

**Comment by richardjrossiii** [comment] 2016-02-29 21:15
Duplicate of #88

**Closed by richardjrossiii** 2016-02-29 21:15 UTC
Labels: duplicate
