### ISSUE TITLE
ParseUser.LogOut() Hangs Unity 5.3.0

### ISSUE THREAD

**Issue by dhanrajsinh24** [ParsePlatform/Parse-SDK-dotNET#140] opened 2015-12-25 15:16 UTC
I am having problems in Unity 5.3.0. When i call "ParseUser.LogOut()", Unity Hangs and i have to force close Unity and start it again.

**Comment by richardjrossiii** [comment] 2016-01-05 20:06
Duplicate of #114.

This appears to be an issue with the unity editor itself, and unless additional evidence can be presented to show that this is not a bug in the unity editor, I'm going to close this.

For the record, I locally tested on Unity 5.3.1f1, and this works as expected:

	// Use this for initialization
	void Start () {
		ParseUser.LogInAsync ("foo", "password").ContinueWith (t => {
			Debug.Log("Logged in user: " + t.Result);

			ParseUser.LogOutAsync().ContinueWith(t2 => {
				Debug.Log("Logged out successfully: " + !t2.IsFaulted);
			});
		});
	}

**Closed** 2016-01-05 20:06 UTC
Labels: duplicate

**Comment by steven-supersolid** [comment] 2016-03-28 19:13
Hi, I've just reproduced this in Unity 5.3.4f1 (current release) and Parse SDK 1.7.0. The problem i found is with ParseUser.Logout(), not with ParseUser.LogoutAsync(), so perhaps Wait() is causing an issue in Unity. The LogOut code is the same in master so the bug is still present.

https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParseCore/Public/ParseUser.cs#L278

```
    public static void LogOut() {
      // TODO (hallucinogen): this will without a doubt fail in Unity. But what else can we do?
      LogOutAsync().Wait();
    }
```

There are a couple of other uses of Wait() in the code, one with another warning comment.

If I switch my code to use LogOutAsync then the problem goes away. This is probably why the workaround in #114 works.

**Comment by richardjrossiii** [comment] 2016-03-28 20:20
Good catch. Eventually, we're going to completely deprecate the synchronous APIs on ParseObjects, as they cause way too much friction and issues for most situations (blocking APIs are bad, folks). Thanks for updating this issue with the workaround you found.
