### ISSUE TITLE
Support for tvOS?

### ISSUE THREAD

**Issue by bbartlett** [ParsePlatform/Parse-SDK-dotNET#56] opened 2015-10-31 00:53 UTC
Any plans for supporting tvOS? From this Parse iOS SDK thread ( https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/250 ), it looks like they are making progress in the native-code side -- can you leverage any of their work?  (Unfortunately, there are definitely still some hurdles to work around such as not having any persistent local storage at all...)

**Comment by richardjrossiii** [comment] 2015-11-02 22:41
Duplicate of #24

**Closed by richardjrossiii** 2015-11-02 22:41 UTC
Labels: duplicate
