### ISSUE TITLE
FormatException: Input string was not in the correct format

### ISSUE THREAD

**Issue by BestStream** [ParsePlatform/Parse-SDK-dotNET#136] opened 2015-12-19 15:06 UTC
I get a lot of errors from users (( 

FormatException: Input string was not in the correct format System.Type.GetTypeFromHandle (RuntimeTypeHandle handle) System.Int32.TryParse (System.String s, Int32& result) Parse.Internal.HttpClient+<>c__DisplayClass10+<>c__DisplayClass16.<ExecuteAsync>b__a (UnityEngine.WWW www) Parse.PlatformHooks+<>c__DisplayClass24.<RegisterNetworkRequest>b__23 () Parse.PlatformHooks+<RunDispatcher>d__2e.MoveNext ()

FormatException: Input string was not in the correct format System.Type.GetTypeFromHandle (RuntimeTypeHandle handle) System.Int32.TryParse (System.String s, Int32& result) Parse.Internal.HttpClient+<>c__DisplayClass10+<>c__DisplayClass16.<ExecuteAsync>b__a (UnityEngine.WWW www) Parse.PlatformHooks+<>c__DisplayClass24.<RegisterNetworkRequest>b__23 () Parse.PlatformHooks+<RunDispatcher>d__2e.MoveNext () Parse.<RunDispatcher>d__2e:MoveNext()

FormatException: Input string was not in the correct format System.Int32.Parse (System.String s)
Parse.Internal.HttpClient.GetStatusCode (UnityEngine.WWW www)
Parse.Internal.HttpClient+<>c__DisplayClass10+<>c__DisplayClass16.<ExecuteAsync>b__a (UnityEngine.WWW www)
Parse.PlatformHooks+<>c__DisplayClass24.<RegisterNetworkRequest>b__23 ()
Parse.PlatformHooks+<RunDispatcher>d__2e.MoveNext ()
UnityEngine.Debug:LogException(Exception)
Parse.<RunDispatcher>d__2e:MoveNext()

**Comment by BestStream** [comment] 2015-12-19 15:07
I have to use Unity4 so I cant upgrade to the latest version of Parse SDK

**Comment by richardjrossiii** [comment] 2015-12-21 18:23
Seeing as we don't support Unity 4 any longer, closing this issue as won't fix. I highly suggest you upgrade to Unity 5.

**Closed by richardjrossiii** 2015-12-21 18:23 UTC
Labels: wontfix

**Comment by BestStream** [comment] 2015-12-21 19:34
As I ritten before, I cann't do it. It is a pity that you simply throw your users

**Comment by BestStream** [comment] 2015-12-21 19:37
You should at least leave the stable version of Unity4 before leaving it

**Comment by iamdain** [comment] 2016-04-25 06:25
@BestStream did you find the cause of this dude? 

We're looking at the opened up code base now, critical we get this sorted. Hit me up on Skype if you'd like to discuss or collaborate - "iamdain"

"upgrade your whole technology stack, graphics pipeline and physics engine" in a dismissive tone is a rather infuriating answer when you're in a bind isn't it...
